FROM ubuntu:18.04

RUN apt update
RUN apt install -y libssl-dev ca-certificates libpq-dev

RUN mkdir -p /cert
COPY ./cert/root-ca.crt /cert
COPY ./cert/ess.encryptizer.com.key /cert
COPY ./cert/ess.encryptizer.com.crt /cert
COPY ./.tmp/web-service /usr/bin/

ENV RUST_LOG DEBUG

ENTRYPOINT [ "web-service" ]
