FROM kamcpp/ess-builder:latest as builder

RUN cargo install diesel_cli --no-default-features --features postgres

# --------------------------------

FROM kamcpp/ess-builder:latest

COPY --from=builder /root/.cargo/bin/diesel /usr/bin/

WORKDIR /work
ADD common/migrations ./migrations
COPY init/init.sh .
