[package]
name = "common"
version = "0.1.0"
authors = ["Kamran Amini <kam.cpp@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.13"
derivative = "2.1.1"
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
